spring.application.name=app
server.port=8080
management.endpoints.web.exposure.include=prometheus,health,info

management.endpoint.prometheus.enabled=true

management.metrics.tags.application=${spring.application.name}

logging.level.root=INFO
logging.level.org.springframework.web=INFO
logging.level.io.micrometer=INFO

spring.main.banner-mode=console
