spring.application.name=app

# Prometheus configurações
management.endpoint.prometheus.enabled=true
management.endpoints.web.exposure.include=health,info,prometheus
management.metrics.export.prometheus.enabled=true
