apiVersion: v1
kind: Secret
metadata:
  name: codigo-vivo-secrets
  namespace: default
type: Opaque
stringData:
  MINIO_ROOT_USER: "admin"
  MINIO_ROOT_PASSWORD: "supersecret"
  SPRING_PROFILES_ACTIVE: "prod"
  MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED: "true"
  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "prometheus,health,info"
